### PR TITLE
Use attr_accessor for the timeout attribute

### PR DESCRIPTION
**Pull request by antstorm**
Here's a small refactor for the `timeout` attribute of the `FFMPEG::Transcoder`. This is more to check the state of the repo, because there's a lot more changes to come.

### CODE REVIEW

**Comment by bikeath1337** [comment]
@antstorm , why not just use `attr_accessor` and make this an instance variable, defaulting to `30`?

**Comment by antstorm** [comment]
@bikeath1337 because that would change the external API, causing backward incompatibility.

**Comment by bikeath1337** [comment]
@antstorm , I'm just starting to review these old PRs and acquaint myself with some of the code. Thanks for pointing that out; it saved me some work!

**Comment by antstorm** [comment]
No worries @bikeath1337, glad to help!

**Pull request closed without merging**
